### ISSUE TITLE
Template as class

### ISSUE THREAD

**Issue by samdark** [yiisoft/view#122]
See https://gist.github.com/samdark/17b63972691bd3a3721c0b11361de920

Related to:

- https://github.com/yiisoft/view/issues/94
- https://github.com/yiisoft/view/issues/19

**Comment by mapeveri** [comment]
@samdark I would like to work on this. Could you tell me the idea of this issue?, Let me explain if I understand you well. The idea with this issue is for getting in a string the content of template, for example your example:

```
$template = (new Template('filename', [data => data]));
$view->render($template);
```

Where the $template variable contains in a string the content of "filename" and with it the view can render it?. Not is totally clear for me, because I saw the render method and I saw this:

```
public function render(string $view, array $parameters = []): string
    {
        $viewFile = $this->findTemplateFile($view);

        return $this->renderFile($viewFile, $parameters);
    }

```

I suppose it's necessary make changes like this:

// (Regarding to @roxblnfk example)
if ($template instanceof TemplateInterface) {
     $injector->make($template)->invoke('render', ...)
 } else {
       $viewFile = $this->findTemplateFile($view);
       return $this->renderFile($viewFile, $parameters);
 }

The class Template should be implement the method render, right?. And this should connect with this:


```
public function renderFile(string $viewFile, array $parameters = []): string
    {
        $parameters = array_merge($this->commonParameters, $parameters);

        // TODO: these two match now
        $requestedFile = $viewFile;

        if ($this->theme !== null) {
            $viewFile = $this->theme->applyTo($viewFile);
        }

        if (is_file($viewFile)) {
            $viewFile = $this->localize($viewFile);
        } else {
            throw new ViewNotFoundException("The view file does not exist: $viewFile");
        }

        $output = '';
        $this->viewFiles[] = [
            'resolved' => $viewFile,
            'requested' => $requestedFile,
        ];

        if ($this->beforeRender($viewFile, $parameters)) {
            $ext = pathinfo($viewFile, PATHINFO_EXTENSION);
            $renderer = $this->renderers[$ext] ?? new PhpTemplateRenderer();
            $output = $renderer->render($this, $viewFile, $parameters);
            $output = $this->afterRender($viewFile, $parameters, $output);
        }

        array_pop($this->viewFiles);

        return $output;
    }

```

Is it correct or or am I saying crazy hahaha? Thanks

**Comment by samdark** [comment]
Noone will explain it better than @roxblnfk.

**Comment by samdark** [comment]
Decided not to implement it for 1.0.0.
